#ifndef _ALLACTIONS_H
#define _ALLACTIONS_H

#include "Action.h"
#include "AddANDgate2.h"
#include "AddNANDgate2.h"
#include "AddORgate2.h"
#include "AddNORgate2.h"
#include "AddXORgate2.h"
#include "AddXNORgate2.h"
#include "AddConnection.h"
#include "AddBuff.h"
#include "AddNOT.h"
#include "AddANDgate3.h"
#include "AddORgate3.h"
#include "AddNORgate3.h"
#include "AddXORgate3.h"
#include "AddXNORgate3.h"
#include "Exit.h"
#include "ChangeToSimulation.h"
#include "ChangeToDesign.h"
#include "SaveFileAction.h"
#include "OpenFileAction.h"
#include "AddLed.h"
#include "AddSwitch.h"
#include "SimModeAction.h"
#include "CreateTruthTable.h"
#include "SelectAction.h"
#include "MoveAction.h"
#include "EditAction.h"
#include "EditConnection.h"
#include "CopyAction.h"
#include "CutAction.h"
#include "PasteAction.h"
#include "DeleteAction.h"

#endif